#ifndef _COMMON_DEFS_INCLUDE
#define _COMMON_DEFS_INCLUDE

#define WINDOW_WIDTH 960
#define WINDOW_HEIGHT 630

#define CAMERA_WIDTH 320
#define CAMERA_HEIGHT 210

#define LEVEL_WIDTH 320
#define LEVEL_HEIGHT 160

#define UI_WIDTH 320
#define UI_HEIGHT 50


enum PixelFormat {TEXTURE_PIXEL_FORMAT_RGB, TEXTURE_PIXEL_FORMAT_RGBA, TEXTURE_PIXEL_FORMAT_L};


#endif //_COMMON_DEFS_INCLUDE


