#ifndef _COMMON_DEFS_INCLUDE
#define _COMMON_DEFS_INCLUDE


#define CAMERA_WIDTH 320
#define CAMERA_HEIGHT 185

#define LEVEL_WIDTH 320
#define LEVEL_HEIGHT 160

#define UI_WIDTH 320
#define UI_HEIGHT 25


enum PixelFormat {TEXTURE_PIXEL_FORMAT_RGB, TEXTURE_PIXEL_FORMAT_RGBA, TEXTURE_PIXEL_FORMAT_L};


#endif //_COMMON_DEFS_INCLUDE


